server:
  port: 8080
spring:
  application:
    name: loan-service
  datasource:
    tomcat:
      max-wait: 20000
      test-on-borrow: true
    url: "jdbc:mysql://localhost:3306/loan"
    username: "develop"
    password: "develop123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false